packages:
  - apps/**
  - '!**/_/**'

catalog:
  '@biomejs/biome': ^2.3.11
  '@cloudflare/puppeteer': ^1.0.4
  '@cloudflare/vite-plugin': ^1.19.0
  '@cloudflare/vitest-pool-workers': ^0.11.1
  '@cloudflare/workers-types': ^4.20260101.0
  '@hono/zod-validator': ^0.7.6
  '@iconify/json': ^2.2.425
  '@scalar/api-reference': ^1.40.9
  '@shazow/whatsabi': ^0.25.0
  '@shikijs/langs': ^3.20.0
  '@shikijs/themes': ^3.20.0
  '@svgr/core': ^8.1.0
  '@svgr/plugin-jsx': ^8.1.0
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/devtools-vite': ^0.4.0
  '@tanstack/query-async-storage-persister': ^5.90.18
  '@tanstack/react-devtools': ^0.9.0
  '@tanstack/react-query': ^5.90.16
  '@tanstack/react-query-devtools': ^5.91.2
  '@tanstack/react-query-persist-client': ^5.90.18
  '@tanstack/react-router': ^1.144.0
  '@tanstack/react-router-devtools': ^1.144.0
  '@tanstack/react-router-ssr-query': ^1.144.0
  '@tanstack/react-start': ^1.145.3
  '@tanstack/router-plugin': ^1.145.2
  '@total-typescript/ts-reset': ^0.6.1
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@wagmi/core': ^3.1.0
  abitype: ^1.2.3
  cva: ^1.0.0-beta.4
  dotenv: ^17.2.3
  eruda: ^3.4.3
  esbuild: ^0.27.2
  globals: ^17.0.0
  hono: ^4.11.3
  hono-rate-limiter: ^0.5.3
  idxs: ^0.0.5
  kysely: ^0.28.9
  ox: ^0.11.3
  prool: ^0.2.2
  react: ^19.2.3
  react-dom: ^19.2.3
  shiki: ^3.20.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tempo.ts: ^0.13.0
  testcontainers: ^11.11.0
  tw-animate-css: ^1.4.0
  typed-query-selector: ^2.12.0
  typescript: ^5.9.3
  unplugin-icons: ^22.5.0
  viem: ^2.44.0
  vite: npm:rolldown-vite@latest
  vite-plugin-devtools-json: ^1.0.0
  vitest: 3.2.4
  wagmi: ^3.2.0
  wrangler: ^4.56.0
  zod: ^4.3.5

catalogMode: strict

enablePrePostScripts: true

nodeOptions: '--disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning'

shellEmulator: true

workspaceConcurrency: -1
