packages:
  - apps/**
  - '!**/_/**'

shellEmulator: true
workspaceConcurrency: -1
enablePrePostScripts: true
nodeOptions: '--disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning'

catalog:
  '@biomejs/biome': ^2.3.10
  '@cloudflare/puppeteer': ^1.0.4
  '@cloudflare/vite-plugin': ^1.19.0
  '@cloudflare/vitest-pool-workers': ^0.11.1
  '@cloudflare/workers-types': ^4.20251225.0
  '@hono/zod-validator': ^0.7.6
  '@iconify/json': ^2.2.421
  '@scalar/api-reference': ^1.40.9
  '@shazow/whatsabi': ^0.25.0
  '@shikijs/langs': ^3.20.0
  '@shikijs/themes': ^3.20.0
  '@svgr/core': ^8.1.0
  '@svgr/plugin-jsx': ^8.1.0
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/devtools-vite': ^0.3.12
  '@tanstack/query-async-storage-persister': ^5.90.14
  '@tanstack/react-devtools': ^0.8.6
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': ^5.91.1
  '@tanstack/react-query-persist-client': ^5.90.14
  '@tanstack/react-router': ^1.143.11
  '@tanstack/react-router-devtools': ^1.143.11
  '@tanstack/react-router-ssr-query': ^1.143.11
  '@tanstack/react-start': ^1.143.11
  '@tanstack/router-plugin': ^1.143.11
  '@total-typescript/ts-reset': ^0.6.1
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  abitype: ^1.2.3
  cva: ^1.0.0-beta.4
  eruda: ^3.4.3
  esbuild: ^0.27.2
  globals: ^16.5.0
  hono: ^4.11.2
  hono-rate-limiter: ^0.5.2
  idxs: ^0.0.5
  kysely: ^0.28.9
  ox: ^0.11.1
  react: ^19.2.3
  react-dom: ^19.2.3
  shiki: ^3.20.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tempo.ts: ^0.12.1
  tw-animate-css: ^1.4.0
  typed-query-selector: ^2.12.0
  typescript: ^5.9.3
  unplugin-icons: ^22.5.0
  viem: ^2.43.3
  vite: npm:rolldown-vite@latest
  vite-plugin-devtools-json: ^1.0.0
  vitest: 3.2.4
  wagmi: ^3.1.3
  wrangler: ^4.56.0
  zod: ^4.2.1

catalogMode: strict
