packages:
  - apps/**
  - '!**/_/**'

catalog:
  '@biomejs/biome': ^2.3.11
  '@cloudflare/puppeteer': ^1.0.5
  '@cloudflare/vite-plugin': ^1.21.1
  '@cloudflare/vitest-pool-workers': ^0.12.5
  '@cloudflare/workers-types': ^4.20260120.0
  '@hono/zod-validator': ^0.7.6
  '@iconify/json': ^2.2.427
  '@scalar/api-reference': ^1.43.10
  '@shazow/whatsabi': ^0.25.0
  '@shikijs/langs': ^3.21.0
  '@shikijs/themes': ^3.21.0
  '@svgr/core': ^8.1.0
  '@svgr/plugin-jsx': ^8.1.0
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/devtools-vite': ^0.4.1
  '@tanstack/query-async-storage-persister': ^5.90.21
  '@tanstack/react-devtools': ^0.9.2
  '@tanstack/react-query': ^5.90.19
  '@tanstack/react-query-devtools': ^5.91.2
  '@tanstack/react-query-persist-client': ^5.90.21
  '@tanstack/react-router': ^1.154.5
  '@tanstack/react-router-devtools': ^1.154.5
  '@tanstack/react-router-ssr-query': ^1.154.5
  '@tanstack/react-start': ^1.154.5
  '@tanstack/router-plugin': ^1.154.5
  '@total-typescript/ts-reset': ^0.6.1
  '@types/animejs': ^3.1.13
  '@types/node': ^25.0.9
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/ui': 3.2.4
  '@wagmi/core': ^3.3.0
  abitype: ^1.2.3
  animejs: ^4.3.1
  cva: ^1.0.0-beta.4
  dotenv: ^17.2.3
  eruda: ^3.4.3
  esbuild: ^0.27.2
  globals: ^17.0.0
  hono: ^4.11.4
  hono-rate-limiter: ^0.5.3
  idxs: ^0.0.6
  jsonc-parser: ^3.3.1
  kysely: ^0.28.10
  ox: ^0.11.3
  prool: ^0.2.2
  react: ^19.2.3
  react-dom: ^19.2.3
  rollup-plugin-visualizer: ^6.0.5
  shiki: ^3.21.0
  sonda: ^0.10.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tempo.ts: ^0.14.0
  testcontainers: ^11.11.0
  tw-animate-css: ^1.4.0
  typed-query-selector: ^2.12.0
  typescript: ^5.9.3
  unplugin-icons: ^23.0.1
  viem: ^2.44.4
  vite: npm:rolldown-vite@latest
  vite-plugin-devtools-json: ^1.0.0
  vitest: 3.2.4
  wagmi: ^3.4.0
  wrangler: ^4.60.0
  zod: ^4.3.5

catalogMode: strict

enablePrePostScripts: true

ignoredBuiltDependencies:
  - bufferutil
  - cbor-extract
  - cpu-features
  - protobufjs
  - sharp
  - ssh2
  - vue-demi

nodeOptions: '--disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning'

onlyBuiltDependencies:
  - '@ast-grep/cli'
  - esbuild
  - utf-8-validate
  - workerd

shellEmulator: true

workspaceConcurrency: -1
