/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAddressRouteImport } from './routes/_layout/$address'
import { Route as LayoutMultisigIndexRouteImport } from './routes/_layout/multisig/index'
import { Route as LayoutMultisigTestRouteImport } from './routes/_layout/multisig/test'
import { Route as LayoutMultisigAddressRouteImport } from './routes/_layout/multisig/$address'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAddressRoute = LayoutAddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMultisigIndexRoute = LayoutMultisigIndexRouteImport.update({
  id: '/multisig/',
  path: '/multisig/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMultisigTestRoute = LayoutMultisigTestRouteImport.update({
  id: '/multisig/test',
  path: '/multisig/test',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMultisigAddressRoute = LayoutMultisigAddressRouteImport.update({
  id: '/multisig/$address',
  path: '/multisig/$address',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$address': typeof LayoutAddressRoute
  '/': typeof LayoutIndexRoute
  '/multisig/$address': typeof LayoutMultisigAddressRoute
  '/multisig/test': typeof LayoutMultisigTestRoute
  '/multisig': typeof LayoutMultisigIndexRoute
}
export interface FileRoutesByTo {
  '/$address': typeof LayoutAddressRoute
  '/': typeof LayoutIndexRoute
  '/multisig/$address': typeof LayoutMultisigAddressRoute
  '/multisig/test': typeof LayoutMultisigTestRoute
  '/multisig': typeof LayoutMultisigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/$address': typeof LayoutAddressRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/multisig/$address': typeof LayoutMultisigAddressRoute
  '/_layout/multisig/test': typeof LayoutMultisigTestRoute
  '/_layout/multisig/': typeof LayoutMultisigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$address'
    | '/'
    | '/multisig/$address'
    | '/multisig/test'
    | '/multisig'
  fileRoutesByTo: FileRoutesByTo
  to: '/$address' | '/' | '/multisig/$address' | '/multisig/test' | '/multisig'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$address'
    | '/_layout/'
    | '/_layout/multisig/$address'
    | '/_layout/multisig/test'
    | '/_layout/multisig/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$address': {
      id: '/_layout/$address'
      path: '/$address'
      fullPath: '/$address'
      preLoaderRoute: typeof LayoutAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/multisig/': {
      id: '/_layout/multisig/'
      path: '/multisig'
      fullPath: '/multisig'
      preLoaderRoute: typeof LayoutMultisigIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/multisig/test': {
      id: '/_layout/multisig/test'
      path: '/multisig/test'
      fullPath: '/multisig/test'
      preLoaderRoute: typeof LayoutMultisigTestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/multisig/$address': {
      id: '/_layout/multisig/$address'
      path: '/multisig/$address'
      fullPath: '/multisig/$address'
      preLoaderRoute: typeof LayoutMultisigAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAddressRoute: typeof LayoutAddressRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMultisigAddressRoute: typeof LayoutMultisigAddressRoute
  LayoutMultisigTestRoute: typeof LayoutMultisigTestRoute
  LayoutMultisigIndexRoute: typeof LayoutMultisigIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAddressRoute: LayoutAddressRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMultisigAddressRoute: LayoutMultisigAddressRoute,
  LayoutMultisigTestRoute: LayoutMultisigTestRoute,
  LayoutMultisigIndexRoute: LayoutMultisigIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
