name: Feature Request
description: Request a feature to be added to a Tempo app.
body:
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you need or want to happen.
    validations:
      required: true
