export const MULTISIG_ABI = [
	{
		type: 'function',
		name: 'threshold',
		inputs: [],
		outputs: [{ type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getTxCount',
		inputs: [],
		outputs: [{ type: 'uint256' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getOwners',
		inputs: [],
		outputs: [{ type: 'address[]' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getTx',
		inputs: [{ name: 'txId', type: 'uint256' }],
		outputs: [
			{ name: 'to', type: 'address' },
			{ name: 'value', type: 'uint256' },
			{ name: 'data', type: 'bytes' },
			{ name: 'executed', type: 'bool' },
			{ name: 'cancelled', type: 'bool' },
			{ name: 'confirmations', type: 'uint256' },
			{ name: 'cancelConfirmations', type: 'uint256' },
			{ name: 'submitTime', type: 'uint256' },
			{ name: 'expiresAt', type: 'uint256' },
			{ name: 'gasLimit', type: 'uint256' },
			{ name: 'submitter', type: 'address' },
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getConfirmations',
		inputs: [{ name: 'txId', type: 'uint256' }],
		outputs: [{ type: 'address[]' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'submit',
		inputs: [
			{ name: 'to', type: 'address' },
			{ name: 'value', type: 'uint256' },
			{ name: 'data', type: 'bytes' },
			{ name: 'gasLimit', type: 'uint256' },
			{ name: 'expiry', type: 'uint256' },
		],
		outputs: [{ type: 'uint256' }],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'confirm',
		inputs: [{ name: 'txId', type: 'uint256' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'revoke',
		inputs: [{ name: 'txId', type: 'uint256' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'execute',
		inputs: [{ name: 'txId', type: 'uint256' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'canExecute',
		inputs: [{ name: 'txId', type: 'uint256' }],
		outputs: [{ type: 'bool' }],
		stateMutability: 'view',
	},
] as const
