/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenarioIdRouteImport } from './routes/scenario.$id'
import { Route as RunIdRouteImport } from './routes/run.$id'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioIdRoute = ScenarioIdRouteImport.update({
  id: '/scenario/$id',
  path: '/scenario/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunIdRoute = RunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/run/$id': typeof RunIdRoute
  '/scenario/$id': typeof ScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/run/$id': typeof RunIdRoute
  '/scenario/$id': typeof ScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/run/$id': typeof RunIdRoute
  '/scenario/$id': typeof ScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/methodology' | '/run/$id' | '/scenario/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/methodology' | '/run/$id' | '/scenario/$id'
  id: '__root__' | '/' | '/methodology' | '/run/$id' | '/scenario/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodologyRoute: typeof MethodologyRoute
  RunIdRoute: typeof RunIdRoute
  ScenarioIdRoute: typeof ScenarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/$id': {
      id: '/scenario/$id'
      path: '/scenario/$id'
      fullPath: '/scenario/$id'
      preLoaderRoute: typeof ScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$id': {
      id: '/run/$id'
      path: '/run/$id'
      fullPath: '/run/$id'
      preLoaderRoute: typeof RunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodologyRoute: MethodologyRoute,
  RunIdRoute: RunIdRoute,
  ScenarioIdRoute: ScenarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
