/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkloadIdRouteImport } from './routes/workload.$id'
import { Route as BenchmarkIdRouteImport } from './routes/benchmark.$id'

const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkloadIdRoute = WorkloadIdRouteImport.update({
  id: '/workload/$id',
  path: '/workload/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkIdRoute = BenchmarkIdRouteImport.update({
  id: '/benchmark/$id',
  path: '/benchmark/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/benchmark/$id': typeof BenchmarkIdRoute
  '/workload/$id': typeof WorkloadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/benchmark/$id': typeof BenchmarkIdRoute
  '/workload/$id': typeof WorkloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methodology': typeof MethodologyRoute
  '/benchmark/$id': typeof BenchmarkIdRoute
  '/workload/$id': typeof WorkloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/methodology' | '/benchmark/$id' | '/workload/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/methodology' | '/benchmark/$id' | '/workload/$id'
  id: '__root__' | '/' | '/methodology' | '/benchmark/$id' | '/workload/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodologyRoute: typeof MethodologyRoute
  BenchmarkIdRoute: typeof BenchmarkIdRoute
  WorkloadIdRoute: typeof WorkloadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workload/$id': {
      id: '/workload/$id'
      path: '/workload/$id'
      fullPath: '/workload/$id'
      preLoaderRoute: typeof WorkloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark/$id': {
      id: '/benchmark/$id'
      path: '/benchmark/$id'
      fullPath: '/benchmark/$id'
      preLoaderRoute: typeof BenchmarkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodologyRoute: MethodologyRoute,
  BenchmarkIdRoute: BenchmarkIdRoute,
  WorkloadIdRoute: WorkloadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
