/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ApiTunnelRouteImport } from './routes/api/tunnel'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LayoutTokensRouteImport } from './routes/_layout/tokens'
import { Route as LayoutBlocksRouteImport } from './routes/_layout/blocks'
import { Route as LayoutDemoIndexRouteImport } from './routes/_layout/demo/index'
import { Route as ApiAddressAddressRouteImport } from './routes/api/address/$address'
import { Route as LayoutTxHashRouteImport } from './routes/_layout/tx/$hash'
import { Route as LayoutTokenAddressRouteImport } from './routes/_layout/token/$address'
import { Route as LayoutReceiptHashRouteImport } from './routes/_layout/receipt/$hash'
import { Route as LayoutDemoTxRouteImport } from './routes/_layout/demo/tx'
import { Route as LayoutDemoPaginationRouteImport } from './routes/_layout/demo/pagination'
import { Route as LayoutDemoEmptyStateRouteImport } from './routes/_layout/demo/empty-state'
import { Route as LayoutDemoAddressRouteImport } from './routes/_layout/demo/address'
import { Route as LayoutBlockIdRouteImport } from './routes/_layout/block/$id'
import { Route as LayoutAddressAddressRouteImport } from './routes/_layout/address/$address'
import { Route as LayoutTxHashIndexRouteImport } from './routes/_layout/tx/$hash/index'
import { Route as LayoutTokenAddressIndexRouteImport } from './routes/_layout/token/$address/index'
import { Route as LayoutAddressAddressIndexRouteImport } from './routes/_layout/address/$address/index'
import { Route as ApiTxBalanceChangesHashRouteImport } from './routes/api/tx/balance-changes/$hash'
import { Route as ApiAddressTxsCountAddressRouteImport } from './routes/api/address/txs-count/$address'
import { Route as ApiAddressTotalValueAddressRouteImport } from './routes/api/address/total-value/$address'
import { Route as LayoutTxHashSectionRouteImport } from './routes/_layout/tx/$hash/$section'
import { Route as LayoutTokenAddressSectionRouteImport } from './routes/_layout/token/$address/$section'
import { Route as LayoutAddressAddressSectionRouteImport } from './routes/_layout/address/$address/$section'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTunnelRoute = ApiTunnelRouteImport.update({
  id: '/api/tunnel',
  path: '/api/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTokensRoute = LayoutTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlocksRoute = LayoutBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoIndexRoute = LayoutDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAddressAddressRoute = ApiAddressAddressRouteImport.update({
  id: '/api/address/$address',
  path: '/api/address/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTxHashRoute = LayoutTxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokenAddressRoute = LayoutTokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceiptHashRoute = LayoutReceiptHashRouteImport.update({
  id: '/receipt/$hash',
  path: '/receipt/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoTxRoute = LayoutDemoTxRouteImport.update({
  id: '/demo/tx',
  path: '/demo/tx',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoPaginationRoute = LayoutDemoPaginationRouteImport.update({
  id: '/demo/pagination',
  path: '/demo/pagination',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoEmptyStateRoute = LayoutDemoEmptyStateRouteImport.update({
  id: '/demo/empty-state',
  path: '/demo/empty-state',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoAddressRoute = LayoutDemoAddressRouteImport.update({
  id: '/demo/address',
  path: '/demo/address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlockIdRoute = LayoutBlockIdRouteImport.update({
  id: '/block/$id',
  path: '/block/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAddressAddressRoute = LayoutAddressAddressRouteImport.update({
  id: '/address/$address',
  path: '/address/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTxHashIndexRoute = LayoutTxHashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTxHashRoute,
} as any)
const LayoutTokenAddressIndexRoute = LayoutTokenAddressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTokenAddressRoute,
} as any)
const LayoutAddressAddressIndexRoute =
  LayoutAddressAddressIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAddressAddressRoute,
  } as any)
const ApiTxBalanceChangesHashRoute = ApiTxBalanceChangesHashRouteImport.update({
  id: '/api/tx/balance-changes/$hash',
  path: '/api/tx/balance-changes/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressTxsCountAddressRoute =
  ApiAddressTxsCountAddressRouteImport.update({
    id: '/api/address/txs-count/$address',
    path: '/api/address/txs-count/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAddressTotalValueAddressRoute =
  ApiAddressTotalValueAddressRouteImport.update({
    id: '/api/address/total-value/$address',
    path: '/api/address/total-value/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutTxHashSectionRoute = LayoutTxHashSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => LayoutTxHashRoute,
} as any)
const LayoutTokenAddressSectionRoute =
  LayoutTokenAddressSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => LayoutTokenAddressRoute,
  } as any)
const LayoutAddressAddressSectionRoute =
  LayoutAddressAddressSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => LayoutAddressAddressRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/blocks': typeof LayoutBlocksRoute
  '/tokens': typeof LayoutTokensRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/': typeof LayoutIndexRoute
  '/address/$address': typeof LayoutAddressAddressRouteWithChildren
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/address': typeof LayoutDemoAddressRoute
  '/demo/empty-state': typeof LayoutDemoEmptyStateRoute
  '/demo/pagination': typeof LayoutDemoPaginationRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/receipt/$hash': typeof LayoutReceiptHashRoute
  '/token/$address': typeof LayoutTokenAddressRouteWithChildren
  '/tx/$hash': typeof LayoutTxHashRouteWithChildren
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/demo': typeof LayoutDemoIndexRoute
  '/address/$address/$section': typeof LayoutAddressAddressSectionRoute
  '/token/$address/$section': typeof LayoutTokenAddressSectionRoute
  '/tx/$hash/$section': typeof LayoutTxHashSectionRoute
  '/api/address/total-value/$address': typeof ApiAddressTotalValueAddressRoute
  '/api/address/txs-count/$address': typeof ApiAddressTxsCountAddressRoute
  '/api/tx/balance-changes/$hash': typeof ApiTxBalanceChangesHashRoute
  '/address/$address/': typeof LayoutAddressAddressIndexRoute
  '/token/$address/': typeof LayoutTokenAddressIndexRoute
  '/tx/$hash/': typeof LayoutTxHashIndexRoute
}
export interface FileRoutesByTo {
  '/blocks': typeof LayoutBlocksRoute
  '/tokens': typeof LayoutTokensRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/': typeof LayoutIndexRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/address': typeof LayoutDemoAddressRoute
  '/demo/empty-state': typeof LayoutDemoEmptyStateRoute
  '/demo/pagination': typeof LayoutDemoPaginationRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/receipt/$hash': typeof LayoutReceiptHashRoute
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/demo': typeof LayoutDemoIndexRoute
  '/address/$address/$section': typeof LayoutAddressAddressSectionRoute
  '/token/$address/$section': typeof LayoutTokenAddressSectionRoute
  '/tx/$hash/$section': typeof LayoutTxHashSectionRoute
  '/api/address/total-value/$address': typeof ApiAddressTotalValueAddressRoute
  '/api/address/txs-count/$address': typeof ApiAddressTxsCountAddressRoute
  '/api/tx/balance-changes/$hash': typeof ApiTxBalanceChangesHashRoute
  '/address/$address': typeof LayoutAddressAddressIndexRoute
  '/token/$address': typeof LayoutTokenAddressIndexRoute
  '/tx/$hash': typeof LayoutTxHashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/blocks': typeof LayoutBlocksRoute
  '/_layout/tokens': typeof LayoutTokensRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/address/$address': typeof LayoutAddressAddressRouteWithChildren
  '/_layout/block/$id': typeof LayoutBlockIdRoute
  '/_layout/demo/address': typeof LayoutDemoAddressRoute
  '/_layout/demo/empty-state': typeof LayoutDemoEmptyStateRoute
  '/_layout/demo/pagination': typeof LayoutDemoPaginationRoute
  '/_layout/demo/tx': typeof LayoutDemoTxRoute
  '/_layout/receipt/$hash': typeof LayoutReceiptHashRoute
  '/_layout/token/$address': typeof LayoutTokenAddressRouteWithChildren
  '/_layout/tx/$hash': typeof LayoutTxHashRouteWithChildren
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/_layout/demo/': typeof LayoutDemoIndexRoute
  '/_layout/address/$address/$section': typeof LayoutAddressAddressSectionRoute
  '/_layout/token/$address/$section': typeof LayoutTokenAddressSectionRoute
  '/_layout/tx/$hash/$section': typeof LayoutTxHashSectionRoute
  '/api/address/total-value/$address': typeof ApiAddressTotalValueAddressRoute
  '/api/address/txs-count/$address': typeof ApiAddressTxsCountAddressRoute
  '/api/tx/balance-changes/$hash': typeof ApiTxBalanceChangesHashRoute
  '/_layout/address/$address/': typeof LayoutAddressAddressIndexRoute
  '/_layout/token/$address/': typeof LayoutTokenAddressIndexRoute
  '/_layout/tx/$hash/': typeof LayoutTxHashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/blocks'
    | '/tokens'
    | '/api/health'
    | '/api/search'
    | '/api/tunnel'
    | '/'
    | '/address/$address'
    | '/block/$id'
    | '/demo/address'
    | '/demo/empty-state'
    | '/demo/pagination'
    | '/demo/tx'
    | '/receipt/$hash'
    | '/token/$address'
    | '/tx/$hash'
    | '/api/address/$address'
    | '/demo'
    | '/address/$address/$section'
    | '/token/$address/$section'
    | '/tx/$hash/$section'
    | '/api/address/total-value/$address'
    | '/api/address/txs-count/$address'
    | '/api/tx/balance-changes/$hash'
    | '/address/$address/'
    | '/token/$address/'
    | '/tx/$hash/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blocks'
    | '/tokens'
    | '/api/health'
    | '/api/search'
    | '/api/tunnel'
    | '/'
    | '/block/$id'
    | '/demo/address'
    | '/demo/empty-state'
    | '/demo/pagination'
    | '/demo/tx'
    | '/receipt/$hash'
    | '/api/address/$address'
    | '/demo'
    | '/address/$address/$section'
    | '/token/$address/$section'
    | '/tx/$hash/$section'
    | '/api/address/total-value/$address'
    | '/api/address/txs-count/$address'
    | '/api/tx/balance-changes/$hash'
    | '/address/$address'
    | '/token/$address'
    | '/tx/$hash'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/blocks'
    | '/_layout/tokens'
    | '/api/health'
    | '/api/search'
    | '/api/tunnel'
    | '/_layout/'
    | '/_layout/address/$address'
    | '/_layout/block/$id'
    | '/_layout/demo/address'
    | '/_layout/demo/empty-state'
    | '/_layout/demo/pagination'
    | '/_layout/demo/tx'
    | '/_layout/receipt/$hash'
    | '/_layout/token/$address'
    | '/_layout/tx/$hash'
    | '/api/address/$address'
    | '/_layout/demo/'
    | '/_layout/address/$address/$section'
    | '/_layout/token/$address/$section'
    | '/_layout/tx/$hash/$section'
    | '/api/address/total-value/$address'
    | '/api/address/txs-count/$address'
    | '/api/tx/balance-changes/$hash'
    | '/_layout/address/$address/'
    | '/_layout/token/$address/'
    | '/_layout/tx/$hash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTunnelRoute: typeof ApiTunnelRoute
  ApiAddressAddressRoute: typeof ApiAddressAddressRoute
  ApiAddressTotalValueAddressRoute: typeof ApiAddressTotalValueAddressRoute
  ApiAddressTxsCountAddressRoute: typeof ApiAddressTxsCountAddressRoute
  ApiTxBalanceChangesHashRoute: typeof ApiTxBalanceChangesHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/tunnel': {
      id: '/api/tunnel'
      path: '/api/tunnel'
      fullPath: '/api/tunnel'
      preLoaderRoute: typeof ApiTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tokens': {
      id: '/_layout/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof LayoutTokensRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blocks': {
      id: '/_layout/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof LayoutBlocksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/': {
      id: '/_layout/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof LayoutDemoIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/address/$address': {
      id: '/api/address/$address'
      path: '/api/address/$address'
      fullPath: '/api/address/$address'
      preLoaderRoute: typeof ApiAddressAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tx/$hash': {
      id: '/_layout/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof LayoutTxHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/token/$address': {
      id: '/_layout/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof LayoutTokenAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/receipt/$hash': {
      id: '/_layout/receipt/$hash'
      path: '/receipt/$hash'
      fullPath: '/receipt/$hash'
      preLoaderRoute: typeof LayoutReceiptHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/tx': {
      id: '/_layout/demo/tx'
      path: '/demo/tx'
      fullPath: '/demo/tx'
      preLoaderRoute: typeof LayoutDemoTxRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/pagination': {
      id: '/_layout/demo/pagination'
      path: '/demo/pagination'
      fullPath: '/demo/pagination'
      preLoaderRoute: typeof LayoutDemoPaginationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/empty-state': {
      id: '/_layout/demo/empty-state'
      path: '/demo/empty-state'
      fullPath: '/demo/empty-state'
      preLoaderRoute: typeof LayoutDemoEmptyStateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/address': {
      id: '/_layout/demo/address'
      path: '/demo/address'
      fullPath: '/demo/address'
      preLoaderRoute: typeof LayoutDemoAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/block/$id': {
      id: '/_layout/block/$id'
      path: '/block/$id'
      fullPath: '/block/$id'
      preLoaderRoute: typeof LayoutBlockIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/address/$address': {
      id: '/_layout/address/$address'
      path: '/address/$address'
      fullPath: '/address/$address'
      preLoaderRoute: typeof LayoutAddressAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tx/$hash/': {
      id: '/_layout/tx/$hash/'
      path: '/'
      fullPath: '/tx/$hash/'
      preLoaderRoute: typeof LayoutTxHashIndexRouteImport
      parentRoute: typeof LayoutTxHashRoute
    }
    '/_layout/token/$address/': {
      id: '/_layout/token/$address/'
      path: '/'
      fullPath: '/token/$address/'
      preLoaderRoute: typeof LayoutTokenAddressIndexRouteImport
      parentRoute: typeof LayoutTokenAddressRoute
    }
    '/_layout/address/$address/': {
      id: '/_layout/address/$address/'
      path: '/'
      fullPath: '/address/$address/'
      preLoaderRoute: typeof LayoutAddressAddressIndexRouteImport
      parentRoute: typeof LayoutAddressAddressRoute
    }
    '/api/tx/balance-changes/$hash': {
      id: '/api/tx/balance-changes/$hash'
      path: '/api/tx/balance-changes/$hash'
      fullPath: '/api/tx/balance-changes/$hash'
      preLoaderRoute: typeof ApiTxBalanceChangesHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/txs-count/$address': {
      id: '/api/address/txs-count/$address'
      path: '/api/address/txs-count/$address'
      fullPath: '/api/address/txs-count/$address'
      preLoaderRoute: typeof ApiAddressTxsCountAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/total-value/$address': {
      id: '/api/address/total-value/$address'
      path: '/api/address/total-value/$address'
      fullPath: '/api/address/total-value/$address'
      preLoaderRoute: typeof ApiAddressTotalValueAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tx/$hash/$section': {
      id: '/_layout/tx/$hash/$section'
      path: '/$section'
      fullPath: '/tx/$hash/$section'
      preLoaderRoute: typeof LayoutTxHashSectionRouteImport
      parentRoute: typeof LayoutTxHashRoute
    }
    '/_layout/token/$address/$section': {
      id: '/_layout/token/$address/$section'
      path: '/$section'
      fullPath: '/token/$address/$section'
      preLoaderRoute: typeof LayoutTokenAddressSectionRouteImport
      parentRoute: typeof LayoutTokenAddressRoute
    }
    '/_layout/address/$address/$section': {
      id: '/_layout/address/$address/$section'
      path: '/$section'
      fullPath: '/address/$address/$section'
      preLoaderRoute: typeof LayoutAddressAddressSectionRouteImport
      parentRoute: typeof LayoutAddressAddressRoute
    }
  }
}

interface LayoutAddressAddressRouteChildren {
  LayoutAddressAddressSectionRoute: typeof LayoutAddressAddressSectionRoute
  LayoutAddressAddressIndexRoute: typeof LayoutAddressAddressIndexRoute
}

const LayoutAddressAddressRouteChildren: LayoutAddressAddressRouteChildren = {
  LayoutAddressAddressSectionRoute: LayoutAddressAddressSectionRoute,
  LayoutAddressAddressIndexRoute: LayoutAddressAddressIndexRoute,
}

const LayoutAddressAddressRouteWithChildren =
  LayoutAddressAddressRoute._addFileChildren(LayoutAddressAddressRouteChildren)

interface LayoutTokenAddressRouteChildren {
  LayoutTokenAddressSectionRoute: typeof LayoutTokenAddressSectionRoute
  LayoutTokenAddressIndexRoute: typeof LayoutTokenAddressIndexRoute
}

const LayoutTokenAddressRouteChildren: LayoutTokenAddressRouteChildren = {
  LayoutTokenAddressSectionRoute: LayoutTokenAddressSectionRoute,
  LayoutTokenAddressIndexRoute: LayoutTokenAddressIndexRoute,
}

const LayoutTokenAddressRouteWithChildren =
  LayoutTokenAddressRoute._addFileChildren(LayoutTokenAddressRouteChildren)

interface LayoutTxHashRouteChildren {
  LayoutTxHashSectionRoute: typeof LayoutTxHashSectionRoute
  LayoutTxHashIndexRoute: typeof LayoutTxHashIndexRoute
}

const LayoutTxHashRouteChildren: LayoutTxHashRouteChildren = {
  LayoutTxHashSectionRoute: LayoutTxHashSectionRoute,
  LayoutTxHashIndexRoute: LayoutTxHashIndexRoute,
}

const LayoutTxHashRouteWithChildren = LayoutTxHashRoute._addFileChildren(
  LayoutTxHashRouteChildren,
)

interface LayoutRouteChildren {
  LayoutBlocksRoute: typeof LayoutBlocksRoute
  LayoutTokensRoute: typeof LayoutTokensRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAddressAddressRoute: typeof LayoutAddressAddressRouteWithChildren
  LayoutBlockIdRoute: typeof LayoutBlockIdRoute
  LayoutDemoAddressRoute: typeof LayoutDemoAddressRoute
  LayoutDemoEmptyStateRoute: typeof LayoutDemoEmptyStateRoute
  LayoutDemoPaginationRoute: typeof LayoutDemoPaginationRoute
  LayoutDemoTxRoute: typeof LayoutDemoTxRoute
  LayoutReceiptHashRoute: typeof LayoutReceiptHashRoute
  LayoutTokenAddressRoute: typeof LayoutTokenAddressRouteWithChildren
  LayoutTxHashRoute: typeof LayoutTxHashRouteWithChildren
  LayoutDemoIndexRoute: typeof LayoutDemoIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBlocksRoute: LayoutBlocksRoute,
  LayoutTokensRoute: LayoutTokensRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAddressAddressRoute: LayoutAddressAddressRouteWithChildren,
  LayoutBlockIdRoute: LayoutBlockIdRoute,
  LayoutDemoAddressRoute: LayoutDemoAddressRoute,
  LayoutDemoEmptyStateRoute: LayoutDemoEmptyStateRoute,
  LayoutDemoPaginationRoute: LayoutDemoPaginationRoute,
  LayoutDemoTxRoute: LayoutDemoTxRoute,
  LayoutReceiptHashRoute: LayoutReceiptHashRoute,
  LayoutTokenAddressRoute: LayoutTokenAddressRouteWithChildren,
  LayoutTxHashRoute: LayoutTxHashRouteWithChildren,
  LayoutDemoIndexRoute: LayoutDemoIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTunnelRoute: ApiTunnelRoute,
  ApiAddressAddressRoute: ApiAddressAddressRoute,
  ApiAddressTotalValueAddressRoute: ApiAddressTotalValueAddressRoute,
  ApiAddressTxsCountAddressRoute: ApiAddressTxsCountAddressRoute,
  ApiTxBalanceChangesHashRoute: ApiTxBalanceChangesHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
