/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTokensRouteImport } from './routes/_layout/tokens'
import { Route as LayoutBlocksRouteImport } from './routes/_layout/blocks'
import { Route as LayoutTxHashRouteImport } from './routes/_layout/tx/$hash'
import { Route as LayoutTokenAddressRouteImport } from './routes/_layout/token/$address'
import { Route as LayoutDemoTxRouteImport } from './routes/_layout/demo/tx'
import { Route as LayoutDemoAddressRouteImport } from './routes/_layout/demo/address'
import { Route as LayoutBlockIdRouteImport } from './routes/_layout/block/$id'
import { Route as LayoutAddressAddressRouteImport } from './routes/_layout/address/$address'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokensRoute = LayoutTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlocksRoute = LayoutBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTxHashRoute = LayoutTxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokenAddressRoute = LayoutTokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoTxRoute = LayoutDemoTxRouteImport.update({
  id: '/demo/tx',
  path: '/demo/tx',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoAddressRoute = LayoutDemoAddressRouteImport.update({
  id: '/demo/address',
  path: '/demo/address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlockIdRoute = LayoutBlockIdRouteImport.update({
  id: '/block/$id',
  path: '/block/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAddressAddressRoute = LayoutAddressAddressRouteImport.update({
  id: '/address/$address',
  path: '/address/$address',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/blocks': typeof LayoutBlocksRoute
  '/tokens': typeof LayoutTokensRoute
  '/': typeof LayoutIndexRoute
  '/address/$address': typeof LayoutAddressAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/address': typeof LayoutDemoAddressRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRoutesByTo {
  '/blocks': typeof LayoutBlocksRoute
  '/tokens': typeof LayoutTokensRoute
  '/': typeof LayoutIndexRoute
  '/address/$address': typeof LayoutAddressAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/address': typeof LayoutDemoAddressRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/blocks': typeof LayoutBlocksRoute
  '/_layout/tokens': typeof LayoutTokensRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/address/$address': typeof LayoutAddressAddressRoute
  '/_layout/block/$id': typeof LayoutBlockIdRoute
  '/_layout/demo/address': typeof LayoutDemoAddressRoute
  '/_layout/demo/tx': typeof LayoutDemoTxRoute
  '/_layout/token/$address': typeof LayoutTokenAddressRoute
  '/_layout/tx/$hash': typeof LayoutTxHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/blocks'
    | '/tokens'
    | '/'
    | '/address/$address'
    | '/block/$id'
    | '/demo/address'
    | '/demo/tx'
    | '/token/$address'
    | '/tx/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blocks'
    | '/tokens'
    | '/'
    | '/address/$address'
    | '/block/$id'
    | '/demo/address'
    | '/demo/tx'
    | '/token/$address'
    | '/tx/$hash'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/blocks'
    | '/_layout/tokens'
    | '/_layout/'
    | '/_layout/address/$address'
    | '/_layout/block/$id'
    | '/_layout/demo/address'
    | '/_layout/demo/tx'
    | '/_layout/token/$address'
    | '/_layout/tx/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tokens': {
      id: '/_layout/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof LayoutTokensRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blocks': {
      id: '/_layout/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof LayoutBlocksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tx/$hash': {
      id: '/_layout/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof LayoutTxHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/token/$address': {
      id: '/_layout/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof LayoutTokenAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/tx': {
      id: '/_layout/demo/tx'
      path: '/demo/tx'
      fullPath: '/demo/tx'
      preLoaderRoute: typeof LayoutDemoTxRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/address': {
      id: '/_layout/demo/address'
      path: '/demo/address'
      fullPath: '/demo/address'
      preLoaderRoute: typeof LayoutDemoAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/block/$id': {
      id: '/_layout/block/$id'
      path: '/block/$id'
      fullPath: '/block/$id'
      preLoaderRoute: typeof LayoutBlockIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/address/$address': {
      id: '/_layout/address/$address'
      path: '/address/$address'
      fullPath: '/address/$address'
      preLoaderRoute: typeof LayoutAddressAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBlocksRoute: typeof LayoutBlocksRoute
  LayoutTokensRoute: typeof LayoutTokensRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAddressAddressRoute: typeof LayoutAddressAddressRoute
  LayoutBlockIdRoute: typeof LayoutBlockIdRoute
  LayoutDemoAddressRoute: typeof LayoutDemoAddressRoute
  LayoutDemoTxRoute: typeof LayoutDemoTxRoute
  LayoutTokenAddressRoute: typeof LayoutTokenAddressRoute
  LayoutTxHashRoute: typeof LayoutTxHashRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBlocksRoute: LayoutBlocksRoute,
  LayoutTokensRoute: LayoutTokensRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAddressAddressRoute: LayoutAddressAddressRoute,
  LayoutBlockIdRoute: LayoutBlockIdRoute,
  LayoutDemoAddressRoute: LayoutDemoAddressRoute,
  LayoutDemoTxRoute: LayoutDemoTxRoute,
  LayoutTokenAddressRoute: LayoutTokenAddressRoute,
  LayoutTxHashRoute: LayoutTxHashRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
