/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ApiTunnelRouteImport } from './routes/api/tunnel'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCodeRouteImport } from './routes/api/code'
import { Route as LayoutTokensRouteImport } from './routes/_layout/tokens'
import { Route as LayoutBlocksRouteImport } from './routes/_layout/blocks'
import { Route as LayoutDemoIndexRouteImport } from './routes/_layout/demo/index'
import { Route as ApiAddressAddressRouteImport } from './routes/api/address/$address'
import { Route as LayoutTxHashRouteImport } from './routes/_layout/tx/$hash'
import { Route as LayoutTokenAddressRouteImport } from './routes/_layout/token/$address'
import { Route as LayoutReceiptHashRouteImport } from './routes/_layout/receipt/$hash'
import { Route as LayoutDemoTxRouteImport } from './routes/_layout/demo/tx'
import { Route as LayoutDemoPaginationRouteImport } from './routes/_layout/demo/pagination'
import { Route as LayoutDemoEmptyStateRouteImport } from './routes/_layout/demo/empty-state'
import { Route as LayoutDemoAddressRouteImport } from './routes/_layout/demo/address'
import { Route as LayoutBlockIdRouteImport } from './routes/_layout/block/$id'
import { Route as LayoutAddressAddressRouteImport } from './routes/_layout/address/$address'
import { Route as ApiTxTraceHashRouteImport } from './routes/api/tx/trace/$hash'
import { Route as ApiTxBalanceChangesHashRouteImport } from './routes/api/tx/balance-changes/$hash'
import { Route as ApiAddressTxsCountAddressRouteImport } from './routes/api/address/txs-count/$address'
import { Route as ApiAddressTotalValueAddressRouteImport } from './routes/api/address/total-value/$address'
import { Route as ApiAddressEventsAddressRouteImport } from './routes/api/address/events/$address'
import { Route as ApiAddressEventsCountAddressRouteImport } from './routes/api/address/events-count/$address'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTunnelRoute = ApiTunnelRouteImport.update({
  id: '/api/tunnel',
  path: '/api/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeRoute = ApiCodeRouteImport.update({
  id: '/api/code',
  path: '/api/code',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTokensRoute = LayoutTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlocksRoute = LayoutBlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoIndexRoute = LayoutDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAddressAddressRoute = ApiAddressAddressRouteImport.update({
  id: '/api/address/$address',
  path: '/api/address/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTxHashRoute = LayoutTxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTokenAddressRoute = LayoutTokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceiptHashRoute = LayoutReceiptHashRouteImport.update({
  id: '/receipt/$hash',
  path: '/receipt/$hash',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoTxRoute = LayoutDemoTxRouteImport.update({
  id: '/demo/tx',
  path: '/demo/tx',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoPaginationRoute = LayoutDemoPaginationRouteImport.update({
  id: '/demo/pagination',
  path: '/demo/pagination',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoEmptyStateRoute = LayoutDemoEmptyStateRouteImport.update({
  id: '/demo/empty-state',
  path: '/demo/empty-state',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoAddressRoute = LayoutDemoAddressRouteImport.update({
  id: '/demo/address',
  path: '/demo/address',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlockIdRoute = LayoutBlockIdRouteImport.update({
  id: '/block/$id',
  path: '/block/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAddressAddressRoute = LayoutAddressAddressRouteImport.update({
  id: '/address/$address',
  path: '/address/$address',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTxTraceHashRoute = ApiTxTraceHashRouteImport.update({
  id: '/api/tx/trace/$hash',
  path: '/api/tx/trace/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTxBalanceChangesHashRoute = ApiTxBalanceChangesHashRouteImport.update({
  id: '/api/tx/balance-changes/$hash',
  path: '/api/tx/balance-changes/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressTxsCountAddressRoute =
  ApiAddressTxsCountAddressRouteImport.update({
    id: '/api/address/txs-count/$address',
    path: '/api/address/txs-count/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAddressTotalValueAddressRoute =
  ApiAddressTotalValueAddressRouteImport.update({
    id: '/api/address/total-value/$address',
    path: '/api/address/total-value/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAddressEventsAddressRoute = ApiAddressEventsAddressRouteImport.update({
  id: '/api/address/events/$address',
  path: '/api/address/events/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressEventsCountAddressRoute =
  ApiAddressEventsCountAddressRouteImport.update({
    id: '/api/address/events-count/$address',
    path: '/api/address/events-count/$address',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/blocks': typeof LayoutBlocksRoute
  '/tokens': typeof LayoutTokensRoute
  '/api/code': typeof ApiCodeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/': typeof LayoutIndexRoute
  '/address/$address': typeof LayoutAddressAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/address': typeof LayoutDemoAddressRoute
  '/demo/empty-state': typeof LayoutDemoEmptyStateRoute
  '/demo/pagination': typeof LayoutDemoPaginationRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/receipt/$hash': typeof LayoutReceiptHashRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/demo': typeof LayoutDemoIndexRoute
  '/api/address/events-count/$address': typeof ApiAddressEventsCountAddressRoute
  '/api/address/events/$address': typeof ApiAddressEventsAddressRoute
  '/api/address/total-value/$address': typeof ApiAddressTotalValueAddressRoute
  '/api/address/txs-count/$address': typeof ApiAddressTxsCountAddressRoute
  '/api/tx/balance-changes/$hash': typeof ApiTxBalanceChangesHashRoute
  '/api/tx/trace/$hash': typeof ApiTxTraceHashRoute
}
export interface FileRoutesByTo {
  '/blocks': typeof LayoutBlocksRoute
  '/tokens': typeof LayoutTokensRoute
  '/api/code': typeof ApiCodeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/': typeof LayoutIndexRoute
  '/address/$address': typeof LayoutAddressAddressRoute
  '/block/$id': typeof LayoutBlockIdRoute
  '/demo/address': typeof LayoutDemoAddressRoute
  '/demo/empty-state': typeof LayoutDemoEmptyStateRoute
  '/demo/pagination': typeof LayoutDemoPaginationRoute
  '/demo/tx': typeof LayoutDemoTxRoute
  '/receipt/$hash': typeof LayoutReceiptHashRoute
  '/token/$address': typeof LayoutTokenAddressRoute
  '/tx/$hash': typeof LayoutTxHashRoute
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/demo': typeof LayoutDemoIndexRoute
  '/api/address/events-count/$address': typeof ApiAddressEventsCountAddressRoute
  '/api/address/events/$address': typeof ApiAddressEventsAddressRoute
  '/api/address/total-value/$address': typeof ApiAddressTotalValueAddressRoute
  '/api/address/txs-count/$address': typeof ApiAddressTxsCountAddressRoute
  '/api/tx/balance-changes/$hash': typeof ApiTxBalanceChangesHashRoute
  '/api/tx/trace/$hash': typeof ApiTxTraceHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/blocks': typeof LayoutBlocksRoute
  '/_layout/tokens': typeof LayoutTokensRoute
  '/api/code': typeof ApiCodeRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tunnel': typeof ApiTunnelRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/address/$address': typeof LayoutAddressAddressRoute
  '/_layout/block/$id': typeof LayoutBlockIdRoute
  '/_layout/demo/address': typeof LayoutDemoAddressRoute
  '/_layout/demo/empty-state': typeof LayoutDemoEmptyStateRoute
  '/_layout/demo/pagination': typeof LayoutDemoPaginationRoute
  '/_layout/demo/tx': typeof LayoutDemoTxRoute
  '/_layout/receipt/$hash': typeof LayoutReceiptHashRoute
  '/_layout/token/$address': typeof LayoutTokenAddressRoute
  '/_layout/tx/$hash': typeof LayoutTxHashRoute
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/_layout/demo/': typeof LayoutDemoIndexRoute
  '/api/address/events-count/$address': typeof ApiAddressEventsCountAddressRoute
  '/api/address/events/$address': typeof ApiAddressEventsAddressRoute
  '/api/address/total-value/$address': typeof ApiAddressTotalValueAddressRoute
  '/api/address/txs-count/$address': typeof ApiAddressTxsCountAddressRoute
  '/api/tx/balance-changes/$hash': typeof ApiTxBalanceChangesHashRoute
  '/api/tx/trace/$hash': typeof ApiTxTraceHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/blocks'
    | '/tokens'
    | '/api/code'
    | '/api/health'
    | '/api/search'
    | '/api/tunnel'
    | '/'
    | '/address/$address'
    | '/block/$id'
    | '/demo/address'
    | '/demo/empty-state'
    | '/demo/pagination'
    | '/demo/tx'
    | '/receipt/$hash'
    | '/token/$address'
    | '/tx/$hash'
    | '/api/address/$address'
    | '/demo'
    | '/api/address/events-count/$address'
    | '/api/address/events/$address'
    | '/api/address/total-value/$address'
    | '/api/address/txs-count/$address'
    | '/api/tx/balance-changes/$hash'
    | '/api/tx/trace/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blocks'
    | '/tokens'
    | '/api/code'
    | '/api/health'
    | '/api/search'
    | '/api/tunnel'
    | '/'
    | '/address/$address'
    | '/block/$id'
    | '/demo/address'
    | '/demo/empty-state'
    | '/demo/pagination'
    | '/demo/tx'
    | '/receipt/$hash'
    | '/token/$address'
    | '/tx/$hash'
    | '/api/address/$address'
    | '/demo'
    | '/api/address/events-count/$address'
    | '/api/address/events/$address'
    | '/api/address/total-value/$address'
    | '/api/address/txs-count/$address'
    | '/api/tx/balance-changes/$hash'
    | '/api/tx/trace/$hash'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/blocks'
    | '/_layout/tokens'
    | '/api/code'
    | '/api/health'
    | '/api/search'
    | '/api/tunnel'
    | '/_layout/'
    | '/_layout/address/$address'
    | '/_layout/block/$id'
    | '/_layout/demo/address'
    | '/_layout/demo/empty-state'
    | '/_layout/demo/pagination'
    | '/_layout/demo/tx'
    | '/_layout/receipt/$hash'
    | '/_layout/token/$address'
    | '/_layout/tx/$hash'
    | '/api/address/$address'
    | '/_layout/demo/'
    | '/api/address/events-count/$address'
    | '/api/address/events/$address'
    | '/api/address/total-value/$address'
    | '/api/address/txs-count/$address'
    | '/api/tx/balance-changes/$hash'
    | '/api/tx/trace/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiCodeRoute: typeof ApiCodeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTunnelRoute: typeof ApiTunnelRoute
  ApiAddressAddressRoute: typeof ApiAddressAddressRoute
  ApiAddressEventsCountAddressRoute: typeof ApiAddressEventsCountAddressRoute
  ApiAddressEventsAddressRoute: typeof ApiAddressEventsAddressRoute
  ApiAddressTotalValueAddressRoute: typeof ApiAddressTotalValueAddressRoute
  ApiAddressTxsCountAddressRoute: typeof ApiAddressTxsCountAddressRoute
  ApiTxBalanceChangesHashRoute: typeof ApiTxBalanceChangesHashRoute
  ApiTxTraceHashRoute: typeof ApiTxTraceHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/tunnel': {
      id: '/api/tunnel'
      path: '/api/tunnel'
      fullPath: '/api/tunnel'
      preLoaderRoute: typeof ApiTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code': {
      id: '/api/code'
      path: '/api/code'
      fullPath: '/api/code'
      preLoaderRoute: typeof ApiCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tokens': {
      id: '/_layout/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof LayoutTokensRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blocks': {
      id: '/_layout/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof LayoutBlocksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/': {
      id: '/_layout/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof LayoutDemoIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/address/$address': {
      id: '/api/address/$address'
      path: '/api/address/$address'
      fullPath: '/api/address/$address'
      preLoaderRoute: typeof ApiAddressAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tx/$hash': {
      id: '/_layout/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof LayoutTxHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/token/$address': {
      id: '/_layout/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof LayoutTokenAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/receipt/$hash': {
      id: '/_layout/receipt/$hash'
      path: '/receipt/$hash'
      fullPath: '/receipt/$hash'
      preLoaderRoute: typeof LayoutReceiptHashRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/tx': {
      id: '/_layout/demo/tx'
      path: '/demo/tx'
      fullPath: '/demo/tx'
      preLoaderRoute: typeof LayoutDemoTxRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/pagination': {
      id: '/_layout/demo/pagination'
      path: '/demo/pagination'
      fullPath: '/demo/pagination'
      preLoaderRoute: typeof LayoutDemoPaginationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/empty-state': {
      id: '/_layout/demo/empty-state'
      path: '/demo/empty-state'
      fullPath: '/demo/empty-state'
      preLoaderRoute: typeof LayoutDemoEmptyStateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo/address': {
      id: '/_layout/demo/address'
      path: '/demo/address'
      fullPath: '/demo/address'
      preLoaderRoute: typeof LayoutDemoAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/block/$id': {
      id: '/_layout/block/$id'
      path: '/block/$id'
      fullPath: '/block/$id'
      preLoaderRoute: typeof LayoutBlockIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/address/$address': {
      id: '/_layout/address/$address'
      path: '/address/$address'
      fullPath: '/address/$address'
      preLoaderRoute: typeof LayoutAddressAddressRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/tx/trace/$hash': {
      id: '/api/tx/trace/$hash'
      path: '/api/tx/trace/$hash'
      fullPath: '/api/tx/trace/$hash'
      preLoaderRoute: typeof ApiTxTraceHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tx/balance-changes/$hash': {
      id: '/api/tx/balance-changes/$hash'
      path: '/api/tx/balance-changes/$hash'
      fullPath: '/api/tx/balance-changes/$hash'
      preLoaderRoute: typeof ApiTxBalanceChangesHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/txs-count/$address': {
      id: '/api/address/txs-count/$address'
      path: '/api/address/txs-count/$address'
      fullPath: '/api/address/txs-count/$address'
      preLoaderRoute: typeof ApiAddressTxsCountAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/total-value/$address': {
      id: '/api/address/total-value/$address'
      path: '/api/address/total-value/$address'
      fullPath: '/api/address/total-value/$address'
      preLoaderRoute: typeof ApiAddressTotalValueAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/events/$address': {
      id: '/api/address/events/$address'
      path: '/api/address/events/$address'
      fullPath: '/api/address/events/$address'
      preLoaderRoute: typeof ApiAddressEventsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/events-count/$address': {
      id: '/api/address/events-count/$address'
      path: '/api/address/events-count/$address'
      fullPath: '/api/address/events-count/$address'
      preLoaderRoute: typeof ApiAddressEventsCountAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutBlocksRoute: typeof LayoutBlocksRoute
  LayoutTokensRoute: typeof LayoutTokensRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAddressAddressRoute: typeof LayoutAddressAddressRoute
  LayoutBlockIdRoute: typeof LayoutBlockIdRoute
  LayoutDemoAddressRoute: typeof LayoutDemoAddressRoute
  LayoutDemoEmptyStateRoute: typeof LayoutDemoEmptyStateRoute
  LayoutDemoPaginationRoute: typeof LayoutDemoPaginationRoute
  LayoutDemoTxRoute: typeof LayoutDemoTxRoute
  LayoutReceiptHashRoute: typeof LayoutReceiptHashRoute
  LayoutTokenAddressRoute: typeof LayoutTokenAddressRoute
  LayoutTxHashRoute: typeof LayoutTxHashRoute
  LayoutDemoIndexRoute: typeof LayoutDemoIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBlocksRoute: LayoutBlocksRoute,
  LayoutTokensRoute: LayoutTokensRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAddressAddressRoute: LayoutAddressAddressRoute,
  LayoutBlockIdRoute: LayoutBlockIdRoute,
  LayoutDemoAddressRoute: LayoutDemoAddressRoute,
  LayoutDemoEmptyStateRoute: LayoutDemoEmptyStateRoute,
  LayoutDemoPaginationRoute: LayoutDemoPaginationRoute,
  LayoutDemoTxRoute: LayoutDemoTxRoute,
  LayoutReceiptHashRoute: LayoutReceiptHashRoute,
  LayoutTokenAddressRoute: LayoutTokenAddressRoute,
  LayoutTxHashRoute: LayoutTxHashRoute,
  LayoutDemoIndexRoute: LayoutDemoIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiCodeRoute: ApiCodeRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTunnelRoute: ApiTunnelRoute,
  ApiAddressAddressRoute: ApiAddressAddressRoute,
  ApiAddressEventsCountAddressRoute: ApiAddressEventsCountAddressRoute,
  ApiAddressEventsAddressRoute: ApiAddressEventsAddressRoute,
  ApiAddressTotalValueAddressRoute: ApiAddressTotalValueAddressRoute,
  ApiAddressTxsCountAddressRoute: ApiAddressTxsCountAddressRoute,
  ApiTxBalanceChangesHashRoute: ApiTxBalanceChangesHashRoute,
  ApiTxTraceHashRoute: ApiTxTraceHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
