/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ReceiptHashRouteImport } from './routes/receipt/$hash'
import { Route as ExploreValueRouteImport } from './routes/explore/$value'
import { Route as ExploreAccountAddressRouteImport } from './routes/explore/account/$address'

const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptHashRoute = ReceiptHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => ReceiptRoute,
} as any)
const ExploreValueRoute = ExploreValueRouteImport.update({
  id: '/explore/$value',
  path: '/explore/$value',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreAccountAddressRoute = ExploreAccountAddressRouteImport.update({
  id: '/explore/account/$address',
  path: '/explore/account/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/receipt': typeof ReceiptRouteWithChildren
  '/explore/$value': typeof ExploreValueRoute
  '/receipt/$hash': typeof ReceiptHashRoute
  '/explore': typeof ExploreIndexRoute
  '/explore/account/$address': typeof ExploreAccountAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/receipt': typeof ReceiptRouteWithChildren
  '/explore/$value': typeof ExploreValueRoute
  '/receipt/$hash': typeof ReceiptHashRoute
  '/explore': typeof ExploreIndexRoute
  '/explore/account/$address': typeof ExploreAccountAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/receipt': typeof ReceiptRouteWithChildren
  '/explore/$value': typeof ExploreValueRoute
  '/receipt/$hash': typeof ReceiptHashRoute
  '/explore/': typeof ExploreIndexRoute
  '/explore/account/$address': typeof ExploreAccountAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/receipt'
    | '/explore/$value'
    | '/receipt/$hash'
    | '/explore'
    | '/explore/account/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorer'
    | '/receipt'
    | '/explore/$value'
    | '/receipt/$hash'
    | '/explore'
    | '/explore/account/$address'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/receipt'
    | '/explore/$value'
    | '/receipt/$hash'
    | '/explore/'
    | '/explore/account/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRoute
  ReceiptRoute: typeof ReceiptRouteWithChildren
  ExploreValueRoute: typeof ExploreValueRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ExploreAccountAddressRoute: typeof ExploreAccountAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$hash': {
      id: '/receipt/$hash'
      path: '/$hash'
      fullPath: '/receipt/$hash'
      preLoaderRoute: typeof ReceiptHashRouteImport
      parentRoute: typeof ReceiptRoute
    }
    '/explore/$value': {
      id: '/explore/$value'
      path: '/explore/$value'
      fullPath: '/explore/$value'
      preLoaderRoute: typeof ExploreValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/account/$address': {
      id: '/explore/account/$address'
      path: '/explore/account/$address'
      fullPath: '/explore/account/$address'
      preLoaderRoute: typeof ExploreAccountAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReceiptRouteChildren {
  ReceiptHashRoute: typeof ReceiptHashRoute
}

const ReceiptRouteChildren: ReceiptRouteChildren = {
  ReceiptHashRoute: ReceiptHashRoute,
}

const ReceiptRouteWithChildren =
  ReceiptRoute._addFileChildren(ReceiptRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRoute,
  ReceiptRoute: ReceiptRouteWithChildren,
  ExploreValueRoute: ExploreValueRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ExploreAccountAddressRoute: ExploreAccountAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
