/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptHashRouteImport } from './routes/receipt/$hash'

const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptHashRoute = ReceiptHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => ReceiptRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/receipt': typeof ReceiptRouteWithChildren
  '/receipt/$hash': typeof ReceiptHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/receipt': typeof ReceiptRouteWithChildren
  '/receipt/$hash': typeof ReceiptHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/receipt': typeof ReceiptRouteWithChildren
  '/receipt/$hash': typeof ReceiptHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/receipt' | '/receipt/$hash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/receipt' | '/receipt/$hash'
  id: '__root__' | '/' | '/receipt' | '/receipt/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceiptRoute: typeof ReceiptRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$hash': {
      id: '/receipt/$hash'
      path: '/$hash'
      fullPath: '/receipt/$hash'
      preLoaderRoute: typeof ReceiptHashRouteImport
      parentRoute: typeof ReceiptRoute
    }
  }
}

interface ReceiptRouteChildren {
  ReceiptHashRoute: typeof ReceiptHashRoute
}

const ReceiptRouteChildren: ReceiptRouteChildren = {
  ReceiptHashRoute: ReceiptHashRoute,
}

const ReceiptRouteWithChildren =
  ReceiptRoute._addFileChildren(ReceiptRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceiptRoute: ReceiptRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
