name: Publish GitHub Page

on:
  pull_request:
    paths:
      - "apps/tokenlist/**"
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "apps/tokenlist/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  NODE_ENV: production
  NODE_OPTIONS: '--disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning'

jobs:
  pages-directory-listing:
    name: "Directory Listing Index"
    runs-on: ${{ vars.DEPOT_ENABLED == 'true' && 'depot-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: "recursive"
          fetch-depth: 0
          persist-credentials: false

      - name: "Generate Directory Listings"
        uses: jayanta525/github-pages-directory-listing@624ac8c4e56893256d3772f61a88e3b14d54314e
        with:
          FOLDER: apps/tokenlist/data #directory to generate index

      - name: "Upload Artifact"
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: "apps/tokenlist/data" # upload generated folder

  deploy:
    name: "Deploy tokenlist to GitHub Pages"
    # if the branch is main or invoked by workflow_dispatch
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    needs: "pages-directory-listing"
    permissions:
      pages: "write"
      id-token: "write"

    environment:
      name: "tokenlist-github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ vars.DEPOT_ENABLED == 'true' && 'depot-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
