name: Scan GitHub Actions

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  scan-github-actions:
    permissions:
      actions: read
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@bd66336ead0e97e3939428f526dc61fb43db0996 # 2026-09-25T20-13-44Z-bd66336e
    with:
      pin-no-api: true
